services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Atoolo\Security\RealmPropertiesUserLoader:
        arguments:
            - '%env(default::IES_WEBNODE_HOME)%/config/realm.properties'

    Atoolo\Security\SiteKit\UserLoader:
        arguments:
            - '@logger'

    atoolo.security.user.provider.ies-webnode:
        class: Atoolo\Security\UserProvider
        arguments:
            - '@Atoolo\Security\RealmPropertiesUserLoader'

    atoolo.security.user.provider:
        class: Atoolo\Security\UserProvider
        arguments:
            - '@Atoolo\Security\SiteKit\UserLoader'

    Atoolo\Security\SiteKit\AccessMapFactory:
        arguments:
            - '@logger'

    atoolo.security.access.map:
        class: Symfony\Component\Security\Http\AccessMapInterface
        factory: ['@Atoolo\Security\SiteKit\AccessMapFactory', 'create']

    Atoolo\Security\SiteKit\ProtectedPathMatcher:
        arguments:
            - '@atoolo.security.access.map'

    Atoolo\Security\SiteKit\Voter:
        arguments:
            - '@atoolo.security.access.map'
        tags:
            - { name: 'security.voter', priority: 10 }
